#!/bin/sh

# Credit for most of this script goes to:
# @meskarune -> https://github.com/meskarune/i3lock-fancy

IMAGE=/tmp/head_0.png

BLURTYPE="5x4" # 2.90s

import -window root -crop 1920x1080+1920+0 $IMAGE

convert $IMAGE -level 0%,100%,0.6 -blur $BLURTYPE -font Liberation-Sans -pointsize 26 -fill white -gravity Center -annotate +960+200 'Type password to unlock' - | composite -gravity center ~/.i3/lock.png - $IMAGE
i3lock --textcolor=ffffff00 --insidecolor=ffffff1c --ringcolor=ffffff3e --linecolor=ffffff00 --keyhlcolor=00000080 --ringvercolor=00000000 --insidevercolor=0000001c --ringwrongcolor=00000055 --insidewrongcolor=0000001c -i $IMAGE -t
rm $IMAGE
